#!/usr/bin/env python3
"""
Merge China domain/IP rules from upstream sources, deduplicate by exact string match,
output merged YAML files, and compile to MRS via mihomo.

Sources:
  - geoview extracted geosite:cn / geoip:cn (from dlc.dat / geoip.dat)
  - MetaCubeX geo/geosite/cn.yaml / geo/geoip/cn.yaml
  - Loyalsoldier direct.txt / cncidr.txt
  - blackmatrix7 ChinaTest_Domain.txt / ChinaMax_IP.txt
"""

import os
import sys
import subprocess
import urllib.request
from collections import OrderedDict

WORKSPACE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUTPUT_DIR = os.path.join(WORKSPACE, "output")
TMP_DIR = os.path.join(WORKSPACE, "tmp")
MIHOMO_BIN = os.path.join(WORKSPACE, "mihomo")

# --- Source definitions ---

# geoview extracts live at <TMP_DIR>/geosite_cn.txt and geoip_cn.txt
# (generated by workflow before this script runs)

DOMAIN_SOURCES = [
    {
        "name": "v2fly-geolocn",
        "path": os.path.join(TMP_DIR, "geosite_cn.txt"),
        "type": "plain-domain",
    },
    {
        "name": "MetaCubeX",
        "url": "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.yaml",
        "type": "yaml-payload",
    },
    {
        "name": "Loyalsoldier",
        "url": "https://github.com/Loyalsoldier/clash-rules/releases/latest/download/direct.txt",
        "type": "yaml-payload",
    },
    {
        "name": "blackmatrix7",
        "url": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaTest/ChinaTest_Domain.txt",
        "type": "plain-domain",
    },
]

IP_SOURCES = [
    {
        "name": "v2fly-geoip",
        "path": os.path.join(TMP_DIR, "geoip_cn.txt"),
        "type": "plain-ip",
    },
    {
        "name": "MetaCubeX",
        "url": "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.yaml",
        "type": "yaml-payload",
    },
    {
        "name": "Loyalsoldier",
        "url": "https://github.com/Loyalsoldier/clash-rules/releases/latest/download/cncidr.txt",
        "type": "yaml-payload",
    },
    {
        "name": "blackmatrix7",
        "url": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMax/ChinaMax_IP.txt",
        "type": "plain-ip",
    },
]


def download(url, path):
    """Download url to path."""
    if os.path.exists(path):
        print(f"  skipping {path}, already exists")
        return
    print(f"  downloading {url}")
    urllib.request.urlretrieve(url, path)
    print(f"    -> {os.path.getsize(path)} bytes")


def get_source_path(src, prefix=""):
    """Get the local file path for a source (url or local path)."""
    if "path" in src:
        return src["path"]
    tmp_name = prefix + "source_" + src['name'] + ".tmp"
    tmp_path = os.path.join(TMP_DIR, tmp_name)
    download(src["url"], tmp_path)
    return tmp_path


def parse_yaml_payload(path):
    """Parse a YAML file with payload: list."""
    results = []
    in_payload = False
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            stripped = line.rstrip()
            if stripped.startswith("payload:"):
                in_payload = True
                continue
            if not in_payload:
                continue
            s = stripped.strip()
            if not s:
                continue
            if s.startswith("- "):
                item = s[2:].strip()
                if len(item) >= 2 and item[0] in ("'", '"') and item[-1] == item[0]:
                    item = item[1:-1]
                if item:
                    results.append(item)
    return results


def parse_plain_domain(path):
    """Parse plain text file, one domain per line."""
    results = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            results.append(line)
    return results


def parse_v2dat_domain(path):
    """
    Parse v2dat-extracted geosite text file.
    Format:
      domain.com           → domain (suffix match)
      full:domain.com      → full (exact match)
      keyword:xxx          → keyword (skip, not usable in domain format)
      regexp:xxx           → regexp (skip)
    Returns list of (type, value) tuples.
    """
    results = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if line.startswith("full:"):
                results.append(("full", line[5:]))
            elif line.startswith("keyword:"):
                continue  # skip, cannot represent in domain format
            elif line.startswith("regexp:"):
                continue  # skip, cannot represent in domain format
            elif line.startswith("domain:"):
                results.append(("domain", line[7:]))
            else:
                # bare domain (default type in v2dat output)
                results.append(("domain", line))
    return results


def parse_plain_ip(path):
    """Parse plain text IP CIDR file."""
    results = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            results.append(line)
    return results


def normalize_domain_entry(entry):
    """
    Normalize a domain entry for dedup and output.
    Input can be from:
      - yaml-payload: +.domain, .domain, domain
      - plain-domain: domain
    Returns (bare_key, output_entry).
    Output format:
      - +.domain  → DOMAIN-SUFFIX
      - domain   → DOMAIN (exact match)
    """
    s = entry.strip()
    if len(s) >= 2 and s[0] in ("'", '"') and s[-1] == s[0]:
        s = s[1:-1]

    # Already has +. prefix (from yaml sources)
    if s.startswith("+."):
        bare = s[2:]
        return (bare, s)

    # Dot prefix only (from yaml sources)
    if s.startswith("."):
        bare = s[1:]
        return (bare, s)

    # Bare domain (from plain-domain sources)
    return (s, "+." + s)


def normalize_v2dat_domain(entry):
    """
    Normalize a v2dat domain entry.
    Input: (type, value) tuple from parse_v2dat_domain.
    Returns (bare_key, output_entry) or None if should skip.
    """
    rule_type, value = entry
    value = value.strip()

    if rule_type == "full":
        # Exact match: output as bare domain (no +. prefix)
        # mihomo behavior:domain interprets bare domain as DOMAIN (exact)
        return (value, value)

    # domain type: add +. for suffix match
    return (value, "+." + value)


def collect_domains():
    """Collect all domain entries from all sources, deduplicate, sort."""
    os.makedirs(TMP_DIR, exist_ok=True)
    all_items = {}

    for src in DOMAIN_SOURCES:
        print(f"\n  [{src['name']}]")
        filepath = get_source_path(src, "domain_")
        src_type = src["type"]

        if src_type == "v2dat-domain":
            raw_entries = parse_v2dat_domain(filepath)
            print(f"    parsed {len(raw_entries)} entries")
            for entry in raw_entries:
                result = normalize_v2dat_domain(entry)
                if result:
                    bare_key, output_entry = result
                    all_items[bare_key] = output_entry
        elif src_type == "yaml-payload":
            entries = parse_yaml_payload(filepath)
            print(f"    parsed {len(entries)} entries")
            for entry in entries:
                bare_key, output_entry = normalize_domain_entry(entry)
                all_items[bare_key] = output_entry
        elif src_type == "plain-domain":
            entries = parse_plain_domain(filepath)
            print(f"    parsed {len(entries)} entries")
            for entry in entries:
                bare_key, output_entry = normalize_domain_entry(entry)
                all_items[bare_key] = output_entry

    sorted_items = sorted(all_items.values())
    print(f"\n  total unique: {len(sorted_items)}")
    return sorted_items


def collect_ips():
    """Collect all IP CIDR entries from all sources, deduplicate, sort."""
    os.makedirs(TMP_DIR, exist_ok=True)
    ip_all = []

    for src in IP_SOURCES:
        print(f"\n  [{src['name']}]")
        filepath = get_source_path(src, "ip_")
        src_type = src["type"]

        if src_type == "yaml-payload":
            entries = parse_yaml_payload(filepath)
        elif src_type == "plain-ip":
            entries = parse_plain_ip(filepath)
        else:
            entries = []

        print(f"    parsed {len(entries)} entries")
        for entry in entries:
            s = entry.strip()
            if len(s) >= 2 and s[0] in ("'", '"') and s[-1] == s[0]:
                s = s[1:-1]
            ip_all.append((s, s))

    ip_dict = OrderedDict()
    for bare_key, output_entry in sorted(ip_all, key=lambda x: x[0]):
        ip_dict[bare_key] = output_entry

    ips = list(ip_dict.values())
    print(f"\n  total unique: {len(ips)}")
    return ips


def write_yaml(items, path):
    """Write items as YAML payload list."""
    with open(path, "w", encoding="utf-8") as f:
        f.write("payload:\n")
        for item in items:
            if "'" in item:
                escaped = item.replace("'", "''")
                f.write("  - '" + escaped + "'\n")
            elif any(c in item for c in (":", "#", "{", "}", "[", "]", "&", "*", "!", ">", "|")):
                f.write("  - '" + item + "'\n")
            else:
                f.write("  - " + item + "\n")
    print(f"  wrote {path} ({os.path.getsize(path)} bytes)")


def compile_mrs(yaml_path, behavior, output_path):
    """Compile YAML to MRS using mihomo convert-ruleset."""
    if not os.path.exists(MIHOMO_BIN):
        print(f"  [SKIP] mihomo not found at {MIHOMO_BIN}")
        return False

    cmd = [MIHOMO_BIN, "convert-ruleset", behavior, "yaml", yaml_path, output_path]
    print(f"  running: {' '.join(cmd)}")
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        print(f"  ERROR: {result.stderr}")
        return False
    if os.path.exists(output_path):
        print(f"  compiled: {output_path} ({os.path.getsize(output_path)} bytes)")
        return True
    return False


def main():
    print("=" * 60)
    print("China Rules Merge Script")
    print("=" * 60)

    os.makedirs(OUTPUT_DIR, exist_ok=True)

    # --- Domain merge ---
    print("\n--- Domain Sources ---")
    domains = collect_domains()
    domain_yaml = os.path.join(OUTPUT_DIR, "ChinaDomain.yaml")
    write_yaml(domains, domain_yaml)

    domain_mrs = os.path.join(OUTPUT_DIR, "ChinaDomain.mrs")
    compile_mrs(domain_yaml, "domain", domain_mrs)

    # --- IP merge ---
    print("\n--- IP CIDR Sources ---")
    ips = collect_ips()
    ip_yaml = os.path.join(OUTPUT_DIR, "ChinaIP.yaml")
    write_yaml(ips, ip_yaml)

    ip_mrs = os.path.join(OUTPUT_DIR, "ChinaIP.mrs")
    compile_mrs(ip_yaml, "ipcidr", ip_mrs)

    # --- Summary ---
    print("\n" + "=" * 60)
    print("Summary:")
    for f in os.listdir(OUTPUT_DIR):
        fpath = os.path.join(OUTPUT_DIR, f)
        print(f"  {f}: {os.path.getsize(fpath)/1024:.1f} KB")
    print("=" * 60)


if __name__ == "__main__":
    main()
